source 'https://rubygems.org'

gem 'rails', '3.1.2'
gem 'pg'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'jwt'
gem 'rspec-rails', '~> 3.0.0'
gem 'factory_girl_rails', '~> 4.0.0'
gem 'faker', '~> 1.0'
gem 'rack-cors', :require => 'rack/cors' 

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end

gem 'rails-api'