development:
  adapter: postgresql
  encoding: unicode
  database: apellido_nombre_developer_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: apellido_nombre_developer_test
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: apellido_nombre_developer_production
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost