default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: prueba_api_development

test:
  <<: *default
  database: prueba_api_test

production:
  <<: *default
  database: prueba_api_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
